baseURL = "/"
languageCode = "en-us"
title = "James Cooper"
theme = "ezhil"

copyright = "© 2017–20 James Cooper | Banner Attribution: Hilton1949 at English Wikipedia"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-90373702-1"
# Your Disqus sortname.
# disqusShortname = "localhost"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Verbum Domini Manet in Aeternum"
    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]
    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]
    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true
    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "images/favicon.png"

# Main menu which appears below site header.
[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"
[[menu.main]]
    name = "Resume"
    weight = 4
    url = "/resume/"
[[menu.main]]
    name = "Papers"
    weight = 5
    url = "/categories/papers/"
[[menu.main]]
    name = "Sermons"
    weight = 6
    url = "/categories/sermons/"
[[menu.main]]
    name = "Links"
    weight = 7
    url = "/links/"
[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 8

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
# [[params.social]]
# name = "Github"
# icon = "github"
# url = "https://github.com/vividvilla/ezhil"

# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/gohugoio"

# Enable tags.
[taxonomies]
   tag = "tags"
   category = "categories"